name: Schedule Sunday 0700

on:
  push:
  schedule:
    - cron:  '0 7 * * 0'

jobs:
  Add-Update-Label-to-Issues-Weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        env:
          IN_PROGRESS_COLUMN_ID: ${{ secrets.IN_PROGRESS_COLUMN_ID }}
        with:
          script: |
            const { IN_PROGRESS_COLUMN_ID } = process.env;
            console.log("ðŸš€ ~ IN_PROGRESS_COLUMN_ID:", IN_PROGRESS_COLUMN_ID)
            const script = require('./github-actions/trigger-schedule/add-update-label-weekly/add-label.js');
            script({ g: github, c: context }, IN_PROGRESS_COLUMN_ID);
